// The verified authority register.
//
// Every `holding`, `establishes`, `limits`, `matters` and `action` field below was
// written after opening the cited document and reading the passage it rests on. The
// documents were retrieved on 29 August 2026; where a publisher refuses automated
// requests, the retrieval route is recorded in `retrieval` so the claim can be
// re-checked by hand.
//
// `limits` is the load-bearing field. An authority register that only says what a
// source holds invites the reader to stretch it. Each entry therefore states the
// boundary of the holding in the same breath as the holding.

export const VERIFIED_ON = '2026-08-17';
export const ANALYSIS_REVIEWED_ON = '2026-08-29';

export const DUTIES = {
  competence: 'Competence and technological understanding',
  confidentiality: 'Confidentiality and informed consent',
  communication: 'Client communication',
  candor: 'Candor to the tribunal',
  supervision: 'Supervision of lawyers, staff and tools',
  fees: 'Fees, expenses and billing',
  advertising: 'Advertising and client intake',
  disclosure: 'Disclosure or certification to the court',
};

export const PRIMARY = [
  {
    id: 'primary-1',
    source: 'ABA',
    category: 'ABA Guidance',
    title: 'ABA Formal Opinion 512 — Generative Artificial Intelligence Tools',
    citation: 'ABA Comm. on Ethics & Prof’l Responsibility, Formal Op. 512 (July 29, 2024)',
    date: '2024-07-29',
    url: 'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/ethics-opinions/aba-formal-opinion-512.pdf',
    jurisdiction: 'United States · ABA Model Rules',
    authority_type: 'Formal ethics opinion',
    binding: 'Persuasive only. The Model Rules bind no lawyer until a state adopts them; Opinion 512 is the reference text most state opinions are measured against.',
    duties: ['competence', 'confidentiality', 'communication', 'candor', 'supervision', 'fees'],
    abstract: 'The ABA Standing Committee on Ethics and Professional Responsibility applies the Model Rules to generative AI, and reaches a confidentiality conclusion stricter than most lawyers expect.',
    holding: 'Lawyers using generative AI must satisfy their duties of competence, confidentiality, client communication, supervision, meritorious contentions, candor to the tribunal, and reasonable fees. On confidentiality the Committee draws a hard line: because many self-learning GAI tools are built so that their output can lead directly or indirectly to disclosure of information relating to a representation, "a client’s informed consent is required prior to inputting information relating to the representation into such a GAI tool." Consent must be specific — the opinion says that adding general boiler-plate to an engagement letter purporting to authorise GAI use is not sufficient.',
    establishes: 'That the confidentiality analysis turns on the architecture of the tool, not on the lawyer\'s intentions. It also settles the billing question: a lawyer billing hourly must bill actual time expended, so time saved by a GAI tool belongs to the client, not the lawyer. Where a lawyer spends fifteen minutes prompting a tool and then reviews the draft, the opinion says the billable time is those fifteen minutes plus the review — not the hours the task would once have taken. The same reasoning is applied to flat and contingent fees: a flat fee unchanged after a tool makes the work dramatically faster may itself become unreasonable under Rule 1.5.',
    limits: 'Advisory. It binds no lawyer anywhere, and the Committee expressly ties its confidentiality conclusion to the risks and capabilities of GAI tools as they stood at publication in July 2024 — an unusual, and honest, self-limiting footnote. It says nothing about tools that do not receive client information, and it does not resolve whether a closed, non-self-learning, contractually walled deployment triggers the consent requirement at all.',
    matters: 'Almost every state opinion issued since is written in this opinion\'s vocabulary, and the Ninth Circuit\'s sanctions order in Lnu v. Blanche reaches the same structural conclusion from the opposite direction: the violation is not the tool, it is the unverified filing. If you read only one document in this register, read this one — then read the one that governs your jurisdiction, because that is the one that binds you.',
    action: 'Compare your engagement letter against the boiler-plate warning. If your firm\'s AI consent language is a single clause added to a standard retainer, this opinion says it does not do the work you think it does. Separately, check whether your billing narrative can survive the "actual time expended" test.',
    retrieval: 'americanbar.org refuses automated requests (HTTP 403); the PDF was read via the Internet Archive capture of 19 August 2026 of the same URL. The live link works in a browser.',
  },
  {
    id: 'primary-2',
    source: 'California',
    category: 'State Bar Guidance',
    title: 'Practical Guidance for the Use of Generative AI in the Practice of Law — 2026 revision',
    citation: 'State Bar of Cal. Standing Comm. on Prof’l Responsibility & Conduct, Practical Guidance for the Use of Generative Artificial Intelligence in the Practice of Law (rev. May 14, 2026)',
    date: '2026-05-14',
    url: 'https://www.calbar.ca.gov/index.php/legal-professionals/ethics-compliance-practice-resources/ethics/ethics-technology-resources',
    documentUrl: 'https://www.calbar.ca.gov/sites/default/files/portals/0/documents/ethics/Generative-AI-Practical-Guidance.pdf',
    jurisdiction: 'California',
    authority_type: 'State bar practical guidance',
    binding: 'Not a rule and not an ethics opinion. It is guidance the State Bar describes as guiding principles rather than best practices — but the Ninth Circuit cited it in Lnu v. Blanche when identifying the applicable standard for California-based lawyers.',
    duties: ['competence', 'confidentiality', 'supervision', 'fees', 'candor'],
    abstract: 'California was first to publish practical guidance in November 2023 and is the first to revise it for agentic systems that act without prompting.',
    holding: 'The Board of Trustees approved revisions on 14 May 2026 to guidance originally published on 16 November 2023. The revision adds an explicit treatment of agentic AI — systems that can autonomously perform tasks or workflows without human prompting. The guidance is direct about what autonomy does and does not change: agentic capability "does not substitute for a lawyer\'s independent professional judgment, nor does it alter a lawyer\'s existing ethical obligations." What it changes is the difficulty of supervision. Competence now requires understanding the nature and extent of a system\'s autonomy, and the guidance warns against configuring agentic systems so that the system makes substantive legal determinations.',
    establishes: 'That the profession\'s first-published guidance treats agentic AI as a supervision problem rather than a new category of permission. It also carries a flat confidentiality prohibition rather than a consent framework: a lawyer must not input confidential client information into any generative AI solution that lacks adequate confidentiality and security protections, must anonymise client information, and should read the terms of use to determine how inputs are used. The bias section notes that with multiple agents, underlying bias can compound.',
    limits: 'Guidance, not a rule — the State Bar says so on its face, and calls it a living document that will be revised again. It does not create a disciplinary standard of its own; it maps existing Rules of Professional Conduct and the State Bar Act onto a new tool. Separately, the State Bar has circulated proposed amendments to the Rules of Professional Conduct related to artificial intelligence for public comment, which means this guidance describes a position that is still moving.',
    matters: 'California is the jurisdiction where the Ninth Circuit\'s disciplinary rules point for lawyers whose principal office is in the state, so this document is not merely advisory to a California litigator in federal court — it is the content the court reached for. It is also, at present, the only major guidance revised specifically for agentic tools, which is the direction firm deployments are moving.',
    action: 'If you have deployed anything that takes multi-step action on its own — drafting, filing, scheduling, contacting — the agentic section is the part to read. The operative question the guidance poses is not whether you supervised the output but whether you understood the extent of the system\'s autonomy before you switched it on.',
    retrieval: 'Resource page and the linked guidance PDF both retrieved directly on 29 August 2026.',
  },
  {
    id: 'primary-3',
    source: 'Florida',
    category: 'State Bar Guidance',
    title: 'Florida Bar Ethics Opinion 24-1',
    citation: 'Fla. Bar Ethics Op. 24-1 (Jan. 19, 2024)',
    date: '2024-01-19',
    url: 'https://www.floridabar.org/etopinions/opinion-24-1/',
    jurisdiction: 'Florida',
    authority_type: 'Advisory ethics opinion',
    binding: 'Advisory. The opinion states on its face that advisory ethics opinions are not binding.',
    duties: ['competence', 'confidentiality', 'supervision', 'fees', 'advertising'],
    abstract: 'The first state ethics opinion of the generative-AI era, and still the only one that works through client-intake chatbots as an advertising problem.',
    holding: 'Lawyers may use generative AI but must protect confidentiality, remain responsible for their own work product, avoid improper billing, and comply with advertising restrictions. Three conclusions are unusually concrete. First, confidentiality turns on whether the tool is self-learning: the opinion recommends obtaining the affected client\'s informed consent before using a third-party tool if that use would disclose confidential information, and says consent is not required where no confidential information leaves the firm. Second, a lawyer may not delegate to generative AI any act constituting the practice of law, and must verify the accuracy and sufficiency of all research it performs. Third, a chatbot that communicates with prospective clients falls under the lawyer-advertising rules and must disclose that it is an AI program and not a lawyer or firm employee.',
    establishes: 'That the nonlawyer-assistant analogy does real work: the opinion reasons from Florida\'s existing opinions on cloud computing, overseas paralegals, device disposal and metadata, and concludes that a third party operating the tool does not relieve the lawyer of the supervisory duty. On costs it is stricter than most: a lawyer may charge the actual cost of using generative AI on a client\'s matter, must say so in advance and preferably in writing, and — where the actual per-matter cost cannot be determined — may not prorate the subscription but must treat it as overhead. Time spent developing minimal competence in the tool is not chargeable to the client.',
    limits: 'Advisory and Florida-specific; it construes the Rules Regulating The Florida Bar, not the Model Rules. It predates the agentic-tool question entirely, and the opinion itself says these concerns should not be treated as an exhaustive list. It makes no finding about any particular product.',
    matters: 'It arrived six months before ABA 512 and reached the same place on billing by a different route. For any firm running website intake, the chatbot analysis is the most directly operational passage in this whole register: it converts a marketing decision into an advertising-rule compliance question, including the risk that a prospective-client relationship forms without the lawyer knowing.',
    action: 'If your website has a chat widget, check whether it identifies itself as an AI program, whether it carries a disclaimer limiting the firm\'s obligations, and whether it screens for people already represented by counsel. The opinion treats all three as the lawyer\'s responsibility, not the vendor\'s.',
    retrieval: 'floridabar.org returns HTTP 200 to automated requests but serves the opinion body only to browsers; the text was read from the Internet Archive capture of 8 August 2026 of the same URL.',
  },
  {
    id: 'primary-4',
    source: 'NYC Bar',
    category: 'State Bar Guidance',
    title: 'Formal Opinion 2024-5 — Generative AI in the Practice of Law',
    citation: 'N.Y.C. Bar Ass’n Comm. on Prof’l Ethics, Formal Op. 2024-5 (2024)',
    date: '2024-08-07',
    url: 'https://www.nycbar.org/reports/formal-opinion-2024-5-generative-ai-in-the-practice-of-law/',
    jurisdiction: 'New York',
    authority_type: 'Formal ethics opinion',
    binding: 'Advisory. A city bar association opinion construing the New York Rules of Professional Conduct; it binds no one and is not the New York State Bar.',
    duties: [],
    abstract: 'Listed because it exists and is a primary source. Its contents are not characterised here, because this monitor could not retrieve it.',
    holding: null,
    unretrieved: true,
    establishes: 'Nothing is asserted about this opinion\'s reasoning or conclusions. The record establishes only that an opinion of this title and number is published at this URL by the New York City Bar Association.',
    limits: 'nycbar.org sits behind a CAPTCHA challenge that refuses automated retrieval (it answers HTTP 202 with a redirect to a challenge page), and the Internet Archive was unreachable during this review. Every other entry in this register was written after reading the document; this one was not, so no characterisation of its holdings appears here. It is retained rather than deleted because a reader looking for New York guidance should know the opinion exists — but a reader should open it themselves rather than rely on a summary this monitor cannot support.',
    matters: 'New York practitioners have no state-level opinion of comparable prominence, so this is the document most often cited to them. That is precisely why an unread summary of it would be the most damaging thing on this page.',
    action: 'Open the link in a browser and read it directly. If you need a characterisation you can cite, this register is not it.',
    retrieval: 'Not retrieved. Direct request answered HTTP 202 with a CAPTCHA redirect on 29 August 2026; archive retrieval failed. Flagged rather than summarised.',
  },
  {
    id: 'primary-5',
    source: 'D.C. Bar',
    category: 'State Bar Guidance',
    title: 'D.C. Bar Ethics Opinion 388 — Attorneys’ Use of Generative AI in Client Matters',
    citation: 'D.C. Bar Legal Ethics Comm., Op. 388 (Apr. 2024)',
    date: '2024-04-01',
    url: 'https://www.dcbar.org/for-lawyers/legal-ethics/ethics-opinions-210-present/ethics-opinion-388',
    jurisdiction: 'District of Columbia',
    authority_type: 'Ethics opinion',
    binding: 'Advisory, construing the D.C. Rules of Professional Conduct.',
    duties: ['competence', 'confidentiality', 'supervision', 'fees', 'candor'],
    abstract: 'The opinion that states the verification standard in the plainest terms: general-audience generative AI is not a reliable substitute for cite-checking.',
    holding: 'The opinion is confined to generative AI products, and implicates Rules 1.1, 1.2, 1.5, 1.6, 1.16, 3.3, 3.4, 5.1, 5.3 and 8.4. Before using a tool a lawyer must understand how it works and what it does, with regard to its dangers and its limitations, and must either have a reasonable basis for trusting its outputs or review and validate them. It states flatly that current general-audience generative AI is not a reliable substitute for traditional fact- and cite-checking. On confidentiality it directs lawyers to determine whether the provider will access or retain client information, warns that many products on the market are specifically designed to collect and use what users submit, and advises either finding a trustworthy alternative or restricting inputs to non-confidential material.',
    establishes: 'That the billing conclusion is not an ABA idiosyncrasy — D.C. reaches it independently: a lawyer can only bill for the time the lawyer actually spent, and under an hourly agreement the economies produced by the tool must inure to the client\'s benefit. Out-of-pocket GAI expenses may be billed where the client agreed to pay expenses. On supervision, Rules 5.1 and 5.3 require reasonable measures to ensure that supervised lawyers and nonlawyers use these tools consistently with the Rules, which the opinion suggests can include requiring staff to verify confidentiality protections before use.',
    limits: 'Advisory, and jurisdictionally narrow. The Committee expressly notes that the concerns it raises may be resolved or mooted for particular products in the future — so a conclusion resting on how a 2024-era product handled inputs does not automatically survive a change in that product. It does not address agentic systems.',
    matters: 'D.C., the ABA and Florida agree on the billing rule and on the verification rule while construing three different rule sets. That convergence is the strongest signal in this register: a lawyer arguing that the position is unsettled has three independent bodies against them.',
    action: 'Treat the verification duty as non-delegable and document it. The three-jurisdiction convergence means "the tool said so" is not available as a defence in any of them.',
    retrieval: 'Retrieved and read directly on 29 August 2026.',
  },
  {
    id: 'primary-6',
    source: 'M.D. Florida',
    category: 'Judicial Standing Orders',
    title: 'Standing Order of Judge Moe Requiring Disclosure of the Use of Artificial Intelligence',
    citation: 'Standing Order Requiring Disclosure of the Use of Artificial Intelligence, No. 6:24-cv-01987-AGM-RMN (M.D. Fla. May 27, 2026), ECF No. 193',
    date: '2026-05-27',
    url: 'https://www.flmd.uscourts.gov/standing-order-judge-moe-requiring-disclosure-use-artificial-intelligence',
    documentUrl: 'https://www.flmd.uscourts.gov/sites/flmd/files/documents/flmd-moe-standing-order-6-24-cv-1987.pdf',
    jurisdiction: 'U.S. District Court · Middle District of Florida',
    authority_type: 'Judicial standing order',
    binding: 'Binding, and narrowly so. It is a standing order entered on the docket of one case before Judge Anne-Leigh Gaylord Moe. It governs filings in that case. It is not a district-wide local rule.',
    duties: ['disclosure', 'candor', 'competence'],
    abstract: 'The strictest disclosure regime in this register: two permissible certifications, verbatim, under penalty of perjury, with doubt resolved in favour of disclosure.',
    holding: 'Every filing must carry a certification stating whether artificial intelligence was used in its preparation. Only two certification texts are permitted, and they must be reproduced verbatim — the order states that only strict compliance will be recognised, because analysing the latent significance of "substantially compliant" certifications is an inefficient use of the court\'s finite resources. A filing without one of the two certifications may be stricken; if the filing is a motion, complaint or petition, the relief requested may be denied without prejudice. Where a filer is unsure whether something counts as artificial intelligence, the order directs that every doubt be resolved in favour of disclosing that it was used. Conventional Westlaw or LexisNexis research, and ordinary search engines, are expressly carved out and need not be disclosed.',
    establishes: 'That a court can impose a disclosure obligation without prohibiting anything: the order says plainly that no rule prohibits the use of artificial intelligence. Its operative mechanism is the affirmative obligation embedded in the certification itself — the filer certifies under penalty of perjury that they have read each case cited, and that failure to do so where a cited case does not exist or does not stand for the cited proposition may be treated as a Rule 11 violation.',
    limits: 'One judge, one case. It is not the practice of the Middle District of Florida, not the practice of the Orlando Division, and not a signal about any other judge — including Judge Berger in the same district, whose order takes a materially different form. Citing this order for the proposition that "federal courts require AI disclosure" would be a misuse of it.',
    matters: 'It is the clearest available specimen of the verbatim-certification model, and the carve-out for traditional legal research is the sharpest line any court in this register has drawn around what "artificial intelligence" means for disclosure purposes. Given that Westlaw and Lexis both now embed generative features, that carve-out is also the provision most likely to be tested.',
    action: 'If you appear before Judge Moe, copy the certification text out of the order — do not paraphrase it, and do not carry over a certification drafted for another judge. If you do not, read it as a template for what a strict-compliance regime looks like before one lands on your docket.',
    retrieval: 'Court page and the seven-page order PDF both retrieved and read directly on 29 August 2026.',
  },
  {
    id: 'primary-7',
    source: 'M.D. Florida',
    category: 'Judicial Standing Orders',
    title: 'Standing Order of Judge Berger on Generative Artificial Intelligence',
    citation: 'In re: Use of Generative Artificial Intelligence, Standing Order (M.D. Fla. Apr. 2, 2026) (Berger, J.)',
    date: '2026-04-02',
    url: 'https://www.flmd.uscourts.gov/standing-order-judge-berger-ai',
    documentUrl: 'https://www.flmd.uscourts.gov/sites/flmd/files/documents/flmd-berger-standing-order-on-ai.pdf',
    jurisdiction: 'U.S. District Court · Middle District of Florida',
    authority_type: 'Judicial standing order',
    binding: 'Binding on all parties appearing before Judge Wendy W. Berger, through counsel or pro se. Entered in the Jacksonville Division as a general standing order rather than in a single case.',
    duties: ['disclosure', 'candor', 'supervision'],
    abstract: 'The same problem, a materially lighter instrument — a two-option certification with no prescribed wording and an explicit page-limit exemption.',
    holding: 'All parties must certify at the end of any filing either that no generative AI was used in drafting and preparing it, or that where generative AI was used, any AI-drafted language — even if later edited by a human — was personally reviewed by the filer or another human for accuracy, and that all legal citations reference actual, non-fictitious authority and accurately reflect its contents. The certification does not count against page limits. Non-compliant filings may be stricken without substantive consideration and without leave to amend. Numerous failures to comply, or failures to properly review AI-generated content, will result in sanctions up to and including dismissal of claims with prejudice, default, and referral to the licensing authority. All filings remain subject to Rule 11, 28 U.S.C. § 1927, and applicable ethical rules.',
    establishes: 'That two judges of the same district, two months apart, chose different mechanisms for the same risk. Berger prescribes no wording and requires no perjury oath; the substantive requirement is human review of AI-drafted language and verification that every citation is real and accurately characterised. The escalation ladder is stated in the order itself rather than left to Rule 11.',
    limits: 'One judge. It is not a Middle District rule, and it does not govern filings before Judge Moe or any other judge. Its careful phrase "even if later edited by a human" resolves one ambiguity — editing does not launder the obligation — but the order defines neither "generative AI" nor the threshold of use that triggers option two, and it contains no carve-out for embedded research tools.',
    matters: 'Read against the Moe order, this pair is the most useful thing in the register for anyone drafting a firm-wide filing protocol. A protocol built for one of these orders fails the other. The practical lesson is that per-judge checking, not a single national template, is the compliance unit.',
    action: 'Before filing in the Middle District of Florida, check the individual judge\'s standing orders — not the local rules, and not what you did last month in front of a different judge in the same courthouse.',
    retrieval: 'Court page and the two-page order PDF both retrieved and read directly on 29 August 2026.',
  },
  {
    id: 'primary-8',
    source: 'Ninth Circuit',
    category: 'Professional Responsibility',
    title: 'Lnu v. Blanche — Sanctions for Fabricated AI Authorities and Failures of Candor',
    citation: 'Lnu v. Blanche, No. 24-4790 (9th Cir. June 3, 2026) (order) (Paez, Bea, and Forrest, JJ.)',
    date: '2026-06-03',
    url: 'https://cdn.ca9.uscourts.gov/datastore/opinions/2026/06/03/24-4790.pdf',
    jurisdiction: 'U.S. Court of Appeals · Ninth Circuit',
    authority_type: 'Published sanctions order',
    binding: 'Published, and therefore precedential within the Ninth Circuit. The only entry in this register that is law rather than guidance.',
    duties: ['candor', 'competence', 'supervision', 'disclosure'],
    abstract: 'A published sanctions order that says, in terms, that the rules are not violated at the point of research and drafting but at the point of signing and filing.',
    holding: 'Two attorneys filed briefs containing multiple nonexistent cases, misattributed quotations and gross misrepresentations of real cases, then represented the errors as typographical mistakes and denied that generative AI might have produced them. The panel imposed sanctions of $2,500 each, suspended both from practice before the court for six months, ordered them to serve the order on their clients, opposing counsel and the presiding judge in every pending matter and on every attorney at their firm, required all firm attorneys for two years to certify under penalty of perjury in every filing whether generative AI was used, naming the tool and certifying personal review of all citations and quotations, and directed the Clerk to serve the order on the State Bar of California.',
    establishes: 'The clearest available statement of where the duty attaches. The panel states that it does not sanction the attorneys for the simple fact that they or their subordinates used generative AI; the rules are not violated at the point of research and drafting, but at the point of signing and filing. If a brief contains cases or quotations that do not exist, it generally does not matter whether the hallucination came from an AI tool or from the lawyer\'s own natural intelligence. The order is equally clear about what drove the severity: had the attorneys disclosed in their Motion to Correct that AI had been used against firm policy and apologised for failing to check the brief, lesser sanctions may have been warranted. The gravity of the discipline was owed to the repeated failure of candor, not to the use of the tool.',
    limits: 'It is a disciplinary order under Federal Rule of Appellate Procedure 46(b) and Ninth Circuit Rule 46-2, applying the California Rules of Professional Conduct because the attorneys\' principal office was in California. It does not create a duty to disclose AI use — the two-year certification requirement is a sanction imposed on these attorneys and their firm, not a rule of general application. It does not hold that using generative AI is misconduct, and the panel cites both the Ninth Circuit\'s own advisory committee note and California authority for the proposition that there is nothing inherently wrong with appropriate use.',
    matters: 'Every guidance document in this register says verification is the lawyer\'s job. This is the document that shows the price. It also answers the question lawyers actually ask after a hallucinated citation is discovered — what do I do now — and the answer is the opposite of instinct: disclose the source of the error immediately to the court and opposing counsel. The panel says so expressly, and the six-month suspension is what the alternative cost.',
    action: 'Two things. First, if you discover a fabricated citation in something you filed, the order tells you to alert the court and opposing counsel at once and disclose the source of the error — including that it came from a generative tool. Second, note that a firm policy against AI use did not protect the firm here; it became an aggravating fact once the filing went out anyway.',
    retrieval: 'Thirty-page published order retrieved and read directly from the court\'s own server on 29 August 2026.',
  },
].map(entry => ({
  ...entry,
  source_tier: 'Primary authority',
  verified_on: VERIFIED_ON,
  analysis_reviewed_on: ANALYSIS_REVIEWED_ON,
  status: entry.unretrieved ? 'Listed — document not retrieved' : 'Verified official source',
  year: entry.date.slice(0, 4),
}));

export const CONVERGENCE = [
  {
    proposition: 'Time saved by a generative tool belongs to the client, not the lawyer.',
    holdings: ['primary-1', 'primary-5'],
    also: 'Florida Opinion 24-1 reaches the same result through its prohibition on falsely inflated hours and on prorating unallocable subscription costs.',
  },
  {
    proposition: 'The lawyer must verify output; the tool is never the source of the duty being discharged.',
    holdings: ['primary-1', 'primary-3', 'primary-5', 'primary-8'],
    also: 'The Ninth Circuit converts this from an ethical duty into an enforced one.',
  },
  {
    proposition: 'Using generative AI is not itself misconduct.',
    holdings: ['primary-6', 'primary-8'],
    also: 'Judge Moe’s order states that no rule prohibits the use of artificial intelligence; the Ninth Circuit declined to sanction for use alone.',
  },
  {
    proposition: 'Client information may not enter a self-learning tool without informed consent.',
    holdings: ['primary-1', 'primary-3'],
    also: 'California states the duty as a prohibition on inadequately protected tools rather than as a consent framework, which is a stricter default.',
  },
];
